#include "ui_chatroomwidget.h" //This is autogenerated and included in the build
#include "UI/ChatRoomWidget.h"
#include <iostream>
#include "UI/ConnectDialog.h"

ChatRoomWidget::ChatRoomWidget(QWidget *parent): QWidget(parent), ui(new Ui::ChatRoomWidget)
{
    ui->setupUi(this);
    connect(ui->sendButton, &QPushButton::clicked, this, &ChatRoomWidget::onSendClicked);
    connect(ui->joinButton, &QPushButton::clicked, this, &ChatRoomWidget::onJoinClicked);
    connect(&WebSocketManager::instance(), &WebSocketManager::messageReceived,
            this, [this](const QString& msgRoom, const QString& msg) {
        if (msgRoom != QString::fromStdString(cruds.room)) return;  
        addMessageToList(msg);        
    });
    connect(ui->messageField, &QLineEdit::textChanged,this, &ChatRoomWidget::onMessgeBoxChanged);
    connect(ui->chatRoomList, &QListWidget::itemClicked, this, &ChatRoomWidget::reloadChatRoom);
    
    ui->chatArea->setStyleSheet(R"(
            QListWidget::item {
                background-color: #454d53;      
                color: #ffffff;                 
                font-size: 20px;                 
                font-family: "Inter", "Segoe UI", "Noto Sans", "Ubuntu"; 
                padding: 10px 12px;              
                margin-bottom: 6px;              
                border-radius: 8px;              
                border: 1px solid #a4a4a4;     
            }
        )");

    ui->chatRoomList->setStyleSheet(R"(
        QListWidget {
            background-color: #232831;
            border: none;
            padding: 6px;
            font-family: "Inter", "Segoe UI", "Noto Sans", "Ubuntu";
            font-size: 13px;
        }

        QListWidget::item {
            background-color: #454d53;      
            color: #ffffff;                 
            font-size: 20px;                 
            font-family: "Inter", "Segoe UI", "Noto Sans", "Ubuntu"; 
            padding: 10px 12px;              
            margin-bottom: 6px;              
            border-radius: 8px;              
            border: 1px solid #a4a4a4;     
        }


        QListWidget::item:hover {
            background-color: #59626b;      
            color: #ffffff;                 
            border: 1px solid #c0c0c0;     
        }

        QListWidget::item:selected {
            background-color: #3a7afe;      
            color: white;
            border: 1px solid #3a7afe;
        }
    )");

}

void ChatRoomWidget::reloadChatRoom(QListWidgetItem *item)
{

    if (!item) return;
    QString storage = item->text();
    QStringList parts = storage.split(':');

    if (parts.size() == 2) {
        cruds.room = parts[0].toStdString();  
        cruds.user = parts[1].toStdString(); 
    } else {
        qWarning() << "Invalid storage format:" << storage;
    }

    ui->chatroomValue->setText(QString::fromStdString(cruds.room));
    ui->userValue->setText(QString::fromStdString(cruds.user));

    socket  = WebSocketManager::instance().socketForRoom(QString::fromStdString(cruds.room), QString::fromStdString(cruds.user));

    if (!socket) {
    qWarning() << "Failed to get socket for room " << QString::fromStdString(cruds.room);
    return;
    }

    ui->chatArea->clear();
}

void ChatRoomWidget::onMessgeBoxChanged(QString text)
{
    message = text;
    
}

void ChatRoomWidget::addMessageToList(const QString msg)
{
    Message m = WebSocketManager::parseMessage(msg); 

   
    QString display = QString("[%1] %2: %3")
                        .arg(QString::fromStdString(m.channel))
                        .arg(QString::fromStdString(m.username))
                        .arg(QString::fromStdString(m.content));


    if (m.username == cruds.user) {
         QListWidgetItem *item = new QListWidgetItem(display, ui->chatArea);
        item->setTextAlignment(Qt::AlignRight);

        item->setBackground(QBrush(QColor("#3a7afe")));
        item->setForeground(QBrush(Qt::white));
        item->setFont(QFont("Inter", 14, QFont::Bold));


        ui->chatArea->addItem(item);
    } else {
        QListWidgetItem *item = new QListWidgetItem(display, ui->chatArea);
        item->setTextAlignment(Qt::AlignLeft);

        item->setBackground(QBrush(QColor("#454d53")));
        item->setForeground(QBrush(QColor("#e0e0e0")));
        item->setFont(QFont("Inter", 14));

        ui->chatArea->addItem(item);
    }

    
    ui->chatArea->scrollToBottom();
        
}

void ChatRoomWidget::onJoinClicked()
{
    ConnectDialog *connectDialog = new ConnectDialog{};
    if (connectDialog && connectDialog->exec() == QDialog::Accepted)
    {
        cruds = connectDialog->getConnectCruds();
        ui->chatArea->clear();
        qDebug() << QString::fromStdString(cruds.room) << " " <<QString::fromStdString(cruds.user);
        socket  = WebSocketManager::instance().socketForRoom(QString::fromStdString(cruds.room), QString::fromStdString(cruds.user));

        if (!socket) {
            qWarning() << "Failed to get socket for room " << QString::fromStdString(cruds.room);
            return;
        }

    }

    
    ui->chatroomValue->setText(QString::fromStdString(cruds.room));
    ui->userValue->setText(QString::fromStdString(cruds.user));
    
    QString storage = QString("%1:%2")
                        .arg(QString::fromStdString(cruds.room))
                        .arg(QString::fromStdString(cruds.user));

    QListWidgetItem *item = new QListWidgetItem(storage);
    item->setSelected(true);
    
    ui->chatRoomList->addItem(item);

}


void ChatRoomWidget::onSendClicked()
{
    QJsonObject obj;
    obj["type"] = "message";
    obj["content"] = message;

    QJsonDocument doc(obj);
    QString json = QString::fromUtf8(doc.toJson(QJsonDocument::Compact));
    ui->messageField->clear();
    socket->sendTextMessage(json);
}


ChatRoomWidget::~ChatRoomWidget(){delete ui;}