#include "ui_chatroomwidget.h" //This is autogenerated and included in the build
#include "UI/ChatRoomWidget.h"
#include <iostream>
#include "UI/ConnectDialog.h"

ChatRoomWidget::ChatRoomWidget(QWidget *parent): QWidget(parent), ui(new Ui::ChatRoomWidget)
{
    ui->setupUi(this);
    connect(ui->sendButton, &QPushButton::clicked, this, &ChatRoomWidget::onSendClicked);
    connect(ui->joinButton, &QPushButton::clicked, this, &ChatRoomWidget::onJoinClicked);
    connect(&WebSocketManager::instance(), &WebSocketManager::messageReceived,
            this, [this](const QString& msgRoom, const QString& msg) {
        if (msgRoom != QString::fromStdString(cruds.room)) return;  
        addMessageToList(msg);        
    });

}















void ChatRoomWidget::addMessageToList(const QString msg)
{
    Message m = WebSocketManager::parseMessage(msg); 

   
    QString display = QString("[%1] %2: %3")
                        .arg(QString::fromStdString(m.channel))
                        .arg(QString::fromStdString(m.username))
                        .arg(QString::fromStdString(m.content));

    
    ui->chatArea->addItem(display);
    ui->chatArea->scrollToBottom();
        
}

void ChatRoomWidget::onJoinClicked()
{
    ConnectDialog *connectDialog = new ConnectDialog{};
    if (connectDialog && connectDialog->exec() == QDialog::Accepted)
    {
        cruds = connectDialog->getConnectCruds();
        qDebug() << QString::fromStdString(cruds.room) << " " <<QString::fromStdString(cruds.user);
        socket  = WebSocketManager::instance().socketForRoom(QString::fromStdString(cruds.room), QString::fromStdString(cruds.user));

        if (!socket) {
            qWarning() << "Failed to get socket for room " << QString::fromStdString(cruds.room);
            return;
        }

    }

}


void ChatRoomWidget::onSendClicked()
{


}


ChatRoomWidget::~ChatRoomWidget(){delete ui;}