#include "ui_connectdialog.h"  //This is autogenerated and included in the build
#include "UI/ConnectDialog.h"
#include <iostream>


ConnectDialog::ConnectDialog(QWidget *parent): QDialog(parent), ui(new Ui::ConnectDialog)
{
    ui->setupUi(this); 
    connect(ui->connectButton, &QPushButton::clicked, this, &ConnectDialog::onConnectClicked);


}
void ConnectDialog::onConnectClicked()
{
    userName = ui->usernameText->toPlainText().toStdString();
    chatRoomName = ui->chatroomText->toPlainText().toStdString();

    accept();

}

void ConnectDialog::getConnectCruds()
{
    std::cout << "Trying to join "<< this->chatRoomName << " as "<< userName << std::endl;
}

ConnectDialog::~ConnectDialog(){delete ui;}